2022-04-13 09:47:50,824 (69299/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:47:50,824 (69299/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:47:50,826 (69299/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n\n'
2022-04-13 09:49:53,252 (69490/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:49:53,252 (69490/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:49:53,261 (69490/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "cemalokten" does not exist\n\n'
2022-04-13 09:50:19,157 (69507/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:50:19,157 (69507/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:50:19,167 (69507/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "cemalokten" does not exist\n\n'
2022-04-13 09:51:50,273 (69673/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:51:50,273 (69673/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:51:50,283 (69673/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 267, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.OperationalError: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  database "cemalokten" does not exist\n\n'
2022-04-13 09:52:58,390 (69700/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:52:58,391 (69700/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:56:22,282 (69806/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-13 09:56:22,283 (69806/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-13 09:56:34,939 (69806/MainThread) pgcli.pgexecute ERROR - sql: '/c bug_reporting_dev', error: SyntaxError('syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n')
2022-04-13 09:56:34,940 (69806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n\n'
2022-04-13 10:49:04,960 (69806/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^\n')
2022-04-13 10:49:04,962 (69806/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n\n'
2022-04-26 14:30:02,229 (11173/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-26 14:30:02,231 (11173/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-26 14:30:06,364 (11173/MainThread) pgcli.pgexecute ERROR - sql: '/c bug_reporting_dev', error: SyntaxError('syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n')
2022-04-26 14:30:06,365 (11173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /c bug_reporting_dev\n        ^\n\n'
2022-04-26 14:30:16,669 (11173/MainThread) pgcli.pgexecute ERROR - sql: 'SE', error: SyntaxError('syntax error at or near "SE"\nLINE 1: SE\n        ^\n')
2022-04-26 14:30:16,670 (11173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "SE"\nLINE 1: SE\n        ^\n\n'
2022-04-26 14:31:12,251 (11173/MainThread) pgcli.pgexecute ERROR - sql: 'select id from activities_log WHERE user_name=Israa', error: UndefinedColumn('column "israa" does not exist\nLINE 1: select id from activities_log WHERE user_name=Israa\n                                                      ^\n')
2022-04-26 14:31:12,251 (11173/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column "israa" does not exist\nLINE 1: select id from activities_log WHERE user_name=Israa\n                                                      ^\n\n'
2022-04-26 17:25:55,633 (16109/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-26 17:25:55,633 (16109/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-26 17:26:06,357 (16109/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT name FROM projects WHERE name=$1', error: UndefinedParameter('there is no parameter $1\nLINE 1: SELECT name FROM projects WHERE name=$1\n                                             ^\n')
2022-04-26 17:26:06,358 (16109/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedParameter: there is no parameter $1\nLINE 1: SELECT name FROM projects WHERE name=$1\n                                             ^\n\n'
2022-04-26 17:26:11,871 (16109/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT name FROM projects WHERE name=Scouts', error: UndefinedColumn('column "scouts" does not exist\nLINE 1: SELECT name FROM projects WHERE name=Scouts\n                                             ^\n')
2022-04-26 17:26:11,871 (16109/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedColumn: column "scouts" does not exist\nLINE 1: SELECT name FROM projects WHERE name=Scouts\n                                             ^\n\n'
2022-04-27 08:26:22,813 (1709/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-27 08:26:22,813 (1709/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 08:49:27,249 (30398/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-29 08:49:27,249 (30398/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 08:50:19,708 (30398/MainThread) pgcli.pgexecute ERROR - sql: 'select * from bugs', error: UndefinedTable('relation "bugs" does not exist\nLINE 1: select * from bugs\n                      ^\n')
2022-04-29 08:50:19,709 (30398/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: relation "bugs" does not exist\nLINE 1: select * from bugs\n                      ^\n\n'
2022-04-29 08:52:14,626 (30398/MainThread) pgcli.pgexecute ERROR - sql: 'clear', error: SyntaxError('syntax error at or near "clear"\nLINE 1: clear\n        ^\n')
2022-04-29 08:52:14,627 (30398/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "clear"\nLINE 1: clear\n        ^\n\n'
2022-04-29 08:52:30,586 (30447/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-29 08:52:30,586 (30447/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 17:58:19,672 (43388/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-04-29 17:58:19,673 (43388/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-04-29 18:09:24,047 (43388/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT\n      e.*, s.status\n    FROM bugs e\n    JOIN activities_log s ON e.activities_log.bug_id = s.bugs.id WHERE bugs.project_id = 1', error: UndefinedTable('missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON e.activities_log.bug_id = s.bug...\n                                     ^\n')
2022-04-29 18:09:24,050 (43388/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON e.activities_log.bug_id = s.bug...\n                                     ^\n\n'
2022-04-29 18:09:47,179 (43388/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT\n      e.*, s.status\n    FROM bugs e\n    JOIN activities_log s ON s.activities_log.bug_id = e.bugs.id WHERE bugs.project_id = 1', error: UndefinedTable('missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n')
2022-04-29 18:09:47,179 (43388/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n\n'
2022-04-29 18:09:58,762 (43388/MainThread) pgcli.pgexecute ERROR - sql: 'SELECT\n      e.*, s.status\n    FROM bugs e\n    JOIN activities_log s ON s.activities_log.bug_id = e.bugs.id WHERE e.bugs.project_id = 1', error: UndefinedTable('missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n')
2022-04-29 18:09:58,762 (43388/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.UndefinedTable: missing FROM-clause entry for table "activities_log"\nLINE 4:     JOIN activities_log s ON s.activities_log.bug_id = e.bug...\n                                     ^\n\n'
2022-05-11 08:05:45,270 (9644/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 08:05:45,270 (9644/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 08:06:44,331 (9644/MainThread) pgcli.pgexecute ERROR - sql: '\\quit', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\quit\n        ^\n')
2022-05-11 08:06:44,332 (9644/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\quit\n        ^\n\n'
2022-05-11 14:43:15,657 (25729/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:43:15,658 (25729/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:43:16,879 (25729/MainThread) pgcli.pgexecute ERROR - sql: "'", error: SyntaxError('unterminated quoted string at or near "\'"\nLINE 1: \'\n        ^\n')
2022-05-11 14:43:16,880 (25729/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: unterminated quoted string at or near "\'"\nLINE 1: \'\n        ^\n\n'
2022-05-11 14:43:24,821 (25729/MainThread) pgcli.pgexecute ERROR - sql: 'ALTER TABLE bugs\nADD  "github_linksss" VARCHAR,', error: SyntaxError('syntax error at end of input\nLINE 2: ADD  "github_linksss" VARCHAR,\n                                      ^\n')
2022-05-11 14:43:24,822 (25729/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at end of input\nLINE 2: ADD  "github_linksss" VARCHAR,\n                                      ^\n\n'
2022-05-11 14:46:35,453 (25919/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:46:35,453 (25919/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:47:44,871 (25919/MainThread) pgcli.pgexecute ERROR - sql: '\\exit', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n')
2022-05-11 14:47:44,874 (25919/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n\n'
2022-05-11 14:55:03,096 (26928/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:55:03,097 (26928/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:55:12,862 (26928/MainThread) pgcli.main ERROR - sql: '\\c bug_reporting_dev', error: InterfaceError('only protocol 3 supported')
2022-05-11 14:55:12,866 (26928/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-11 14:58:09,728 (27040/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 14:58:09,729 (27040/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 14:58:13,257 (27040/MainThread) pgcli.main ERROR - sql: '\\c d4fik3rlo3r184', error: InterfaceError('only protocol 3 supported')
2022-05-11 14:58:13,262 (27040/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-11 15:08:06,480 (27492/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:08:06,481 (27492/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 15:13:29,047 (28134/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:13:29,047 (28134/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 15:13:51,177 (28134/MainThread) pgcli.pgexecute ERROR - sql: 'TRUNCATE TABLE projects', error: FeatureNotSupported('cannot truncate a table referenced in a foreign key constraint\nDETAIL:  Table "bugs" references "projects".\nHINT:  Truncate table "bugs" at the same time, or use TRUNCATE ... CASCADE.\n')
2022-05-11 15:13:51,181 (28134/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.FeatureNotSupported: cannot truncate a table referenced in a foreign key constraint\nDETAIL:  Table "bugs" references "projects".\nHINT:  Truncate table "bugs" at the same time, or use TRUNCATE ... CASCADE.\n\n'
2022-05-11 15:14:58,869 (28134/MainThread) pgcli.pgexecute ERROR - sql: '/q', error: SyntaxError('syntax error at or near "/"\nLINE 1: /q\n        ^\n')
2022-05-11 15:14:58,870 (28134/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /q\n        ^\n\n'
2022-05-11 15:19:04,836 (28296/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:19:04,836 (28296/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-11 15:20:25,931 (28296/MainThread) pgcli.pgexecute ERROR - sql: '/q', error: SyntaxError('syntax error at or near "/"\nLINE 1: /q\n        ^\n')
2022-05-11 15:20:25,934 (28296/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "/"\nLINE 1: /q\n        ^\n\n'
2022-05-11 15:29:23,923 (28662/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-11 15:29:23,924 (28662/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-16 10:44:24,081 (6427/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-16 10:44:24,081 (6427/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-16 12:11:50,981 (9966/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-16 12:11:50,982 (9966/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-16 12:32:58,614 (9966/MainThread) pgcli.pgexecute ERROR - sql: '\\exit', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n')
2022-05-16 12:32:58,617 (9966/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\exit\n        ^\n\n'
2022-05-18 14:45:23,666 (6021/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 14:45:23,667 (6021/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:37:53,075 (13997/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:37:53,075 (13997/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:40:09,957 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE database shannon-trust', error: SyntaxError('syntax error at or near "-"\nLINE 1: CREATE database shannon-trust\n                               ^\n')
2022-05-18 15:40:09,958 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "-"\nLINE 1: CREATE database shannon-trust\n                               ^\n\n'
2022-05-18 15:40:24,207 (13997/MainThread) pgcli.pgexecute ERROR - sql: "CREATE database 'shannon-trust'", error: SyntaxError('syntax error at or near "\'shannon-trust\'"\nLINE 1: CREATE database \'shannon-trust\'\n                        ^\n')
2022-05-18 15:40:24,207 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\'shannon-trust\'"\nLINE 1: CREATE database \'shannon-trust\'\n                        ^\n\n'
2022-05-18 15:42:01,275 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE database `shannon-trust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE database `shannon-trust`\n                        ^\n')
2022-05-18 15:42:01,276 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE database `shannon-trust`\n                        ^\n\n'
2022-05-18 15:42:15,164 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE `shannon-trust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n')
2022-05-18 15:42:15,164 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n\n'
2022-05-18 15:42:19,266 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE `shannon-trust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n')
2022-05-18 15:42:19,266 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannon-trust`\n                        ^\n\n'
2022-05-18 15:42:50,691 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DB `shannon-trust`', error: SyntaxError('syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n')
2022-05-18 15:42:50,692 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n\n'
2022-05-18 15:42:52,378 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DB `shannon-trust`', error: SyntaxError('syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n')
2022-05-18 15:42:52,379 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "DB"\nLINE 1: CREATE DB `shannon-trust`\n               ^\n\n'
2022-05-18 15:43:19,456 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE [shannon-trust]', error: SyntaxError('syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n')
2022-05-18 15:43:19,456 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n\n'
2022-05-18 15:43:26,044 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE [shannon-trust', error: SyntaxError('syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust\n                        ^\n')
2022-05-18 15:43:26,044 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust\n                        ^\n\n'
2022-05-18 15:43:29,599 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE [shannon-trust]', error: SyntaxError('syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n')
2022-05-18 15:43:29,600 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "["\nLINE 1: CREATE DATABASE [shannon-trust]\n                        ^\n\n'
2022-05-18 15:43:39,555 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'CREATE DATABASE `shannontrust`', error: SyntaxError('syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannontrust`\n                        ^\n')
2022-05-18 15:43:39,555 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "`"\nLINE 1: CREATE DATABASE `shannontrust`\n                        ^\n\n'
2022-05-18 15:43:51,222 (13997/MainThread) pgcli.pgexecute ERROR - sql: '\\CREATE DATABASE `shannon-trust`', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE `shannon-trust`\n        ^\n')
2022-05-18 15:43:51,223 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE `shannon-trust`\n        ^\n\n'
2022-05-18 15:44:09,297 (13997/MainThread) pgcli.pgexecute ERROR - sql: 'q', error: SyntaxError('syntax error at or near "q"\nLINE 1: q\n        ^\n')
2022-05-18 15:44:09,298 (13997/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "q"\nLINE 1: q\n        ^\n\n'
2022-05-18 15:44:51,648 (14643/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:44:51,649 (14643/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:44:58,104 (14643/MainThread) pgcli.pgexecute ERROR - sql: '\\C shannon-trust', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\C shannon-trust\n        ^\n')
2022-05-18 15:44:58,105 (14643/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\C shannon-trust\n        ^\n\n'
2022-05-18 15:45:09,363 (14652/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:45:09,363 (14652/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:45:16,094 (14652/MainThread) pgcli.main ERROR - sql: '\\connect shannon-trust', error: InterfaceError('only protocol 3 supported')
2022-05-18 15:45:16,095 (14652/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-18 15:45:24,480 (14652/MainThread) pgcli.main ERROR - sql: '\\connect `shannon-trust`', error: InterfaceError('only protocol 3 supported')
2022-05-18 15:45:24,481 (14652/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 748, in execute_command\n    output, query = self._evaluate_command(text)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 1007, in _evaluate_command\n    for title, cur, headers, status, sql, success, is_special in res:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 469, in run\n    for result in response:\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/main.py", line 399, in change_db\n    self.pgexecute.connect(\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 313, in connect\n    conn = psycopg2.connect(**conn_params)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect\n    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)\npsycopg2.InterfaceError: only protocol 3 supported\n'
2022-05-18 15:50:32,106 (14733/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-18 15:50:32,106 (14733/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-18 15:50:41,548 (14733/MainThread) pgcli.pgexecute ERROR - sql: '\\CREATE DATABASE shannon_trust', error: SyntaxError('syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE shannon_trust\n        ^\n')
2022-05-18 15:50:41,549 (14733/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "\\"\nLINE 1: \\CREATE DATABASE shannon_trust\n        ^\n\n'
2022-05-19 09:18:32,634 (22125/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 09:18:32,635 (22125/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 09:19:38,391 (22125/MainThread) pgcli.pgexecute ERROR - sql: 'quiot', error: SyntaxError('syntax error at or near "quiot"\nLINE 1: quiot\n        ^\n')
2022-05-19 09:19:38,394 (22125/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "quiot"\nLINE 1: quiot\n        ^\n\n'
2022-05-19 14:05:15,356 (32575/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 14:05:15,357 (32575/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 14:12:27,494 (33487/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 14:12:27,495 (33487/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 14:13:52,063 (34045/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2022-05-19 14:13:52,064 (34045/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2022-05-19 14:13:56,688 (34045/MainThread) pgcli.pgexecute ERROR - sql: '1   DROP TYPE IF EXISTS bug_types CASCADE', error: SyntaxError('syntax error at or near "1"\nLINE 1: 1   DROP TYPE IF EXISTS bug_types CASCADE\n        ^\n')
2022-05-19 14:13:56,690 (34045/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 480, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 515, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/3.4.1/libexec/lib/python3.9/site-packages/pgcli/pgexecute.py", line 175, in execute\n    psycopg2.extensions.cursor.execute(self, sql, args)\npsycopg2.errors.SyntaxError: syntax error at or near "1"\nLINE 1: 1   DROP TYPE IF EXISTS bug_types CASCADE\n        ^\n\n'
